Resources:
  LambdaPowertools6C67E389:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 0033c7d5583c3b4decc5d6275892048fe4d5995c5dbca7414860662cbb17b43a.zip
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
        - python3.9
      Description: Lambda Powertools for Python latest version
      LicenseInfo: MIT-0
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/LambdaPowertools/Resource
      aws:asset:path: /private/var/folders/2p/_fyn48fs31g7nzhtg0_4_jc40000gn/T/cdk-docker-cp-8Qu2pe
      aws:asset:is-bundled: false
      aws:asset:property: Content
  functionServiceRoleEF216095:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/function/ServiceRole/Resource
  functionF19B1A04:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 5ef5449cdf896db0f85a4d589865b12c4659d57d89a69bc6ee0bb62b6d7f50f4.zip
      Role:
        Fn::GetAtt:
          - functionServiceRoleEF216095
          - Arn
      Handler: app.lambda_handler
      Layers:
        - Ref: LambdaPowertools6C67E389
      Runtime: python3.9
    DependsOn:
      - functionServiceRoleEF216095
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/function/Resource
      aws:asset:path: /Users/blake/Github/lambda-powertools-python/cdk.out/asset.5ef5449cdf896db0f85a4d589865b12c4659d57d89a69bc6ee0bb62b6d7f50f4
      aws:asset:is-bundled: true
      aws:asset:property: Code
  httpapi04200D5F:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: httpapi
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/httpapi/Resource
  httpapiDefaultStageEEE9F4E2:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: httpapi04200D5F
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/httpapi/DefaultStage/Resource
  httpapiANYhellointegPermissionF9035168:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - functionF19B1A04
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: httpapi04200D5F
            - /*/*/hello
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/httpapi/ANY--hello/integ-Permission
  httpapiANYhellointegE46EC4EA:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: httpapi04200D5F
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - functionF19B1A04
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/httpapi/ANY--hello/integ/Resource
  httpapiANYhelloE79CA0CD:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: httpapi04200D5F
      RouteKey: ANY /hello
      AuthorizationType: NONE
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: httpapiANYhellointegE46EC4EA
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/httpapi/ANY--hello/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02QTWvDMAyGf0vujps1p97WFsYGg5YMdi1qoqVaEtvY8kow+e+LnWz09OrjtfTIW/lUyFBkcHd53XR5T1cZPhjqTsylS3DlBZxDdnIfRbhSHnzdIR/AoehhuDYgw/FLvcOI9hOtI63EnL94VfMan9EO5GJnEgSDDJXuMTaiTgIMtcB4h/Fnm2btDcXujNEm25tibC38jau0Z5wmkYiiiVQb6yfPxnNyoNPe1unxUauGOO0ucujNDWSRPa/3bqKG5YzcjHzTavWcU/J/xSPj6givzCaiRl1YY5ToUvSAPc24y8RNKXfzn2ffjii3XjENKKtFfwEwchHnjQEAAA==
    Metadata:
      aws:cdk:path: LambdaPowertoolsPythonStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  apiurl:
    Value:
      Fn::GetAtt:
        - httpapi04200D5F
        - ApiEndpoint
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

